### ISSUE TITLE
Create "readme.md"

### ISSUE THREAD

**Issue by KazumaMurao** [openpool/openpool-core#12]
- Decide who is assigned this issue, first.
- Then breakdown "readme.md" to the section such as "install opencv" or "setup openpool on eclipse"
- Some checking parts would be needed before finish writing.

**Comment by KazumaMurao** [comment]
For just as first update of this issue, I assign this to @takashyx .

**Comment by takashyx** [comment]
thanks Kaz :+1: for the first step I added the draft file in the devel branch : readme-draft.txt
let's discuss this in the mtg tomorrow (04/24/2013)
