### ISSUE TITLE
resources/build.properties: modify to the relative path name

### ISSUE THREAD

**Issue by KazumaMurao** [openpool/openpool-core#14]
I found an inappropriate way of file calling in resources/build.properties, resources/build.properties_custom_example. 

The line
${user.home}/Documents/GitHub/openpool-base-kinect/dependency/
restricts openpool-base-kinect directory as under ${user.home}/Documents/GitHub/openpool-base-kinect/dependency/ .

If we locate directory on other place, ant will be failed due to this line.
(Temporarily I solve this problem to copy openpool-base-kinect/dependency to under ${user.home}/Documents/GitHub but this is tricky.)

The goal of this issue is to fix this problem: modify to the relative path name, can run ant from anywhere.

```
$ grep GitHub resources/*
resources/build.properties:classpath.local.location=${user.home}/Documents/GitHub/openpool-base-kinect/dependency/
resources/build.properties:# Recommendations for storing your source code online are Google Code or GitHub.
resources/build.properties:source.host=GitHub
resources/build.properties_custom_example:#classpath.local.location=${user.home}/Documents/GitHub/openpool-base-kinect/dependency/
resources/build.properties_custom_example:# Recommendations for storing your source code online are Google Code or GitHub.
resources/build.properties_custom_example:source.host=GitHub
```

**Comment by KazumaMurao** [comment]
@takashyx san, I send a pull request to solve this issue. Please check running ant, and if there is no problem, merge and close this issue.

**Comment by takashyx** [comment]
Merged! Thanks.
