### ISSUE TITLE
Delete distribution/OpenpoolBaseKinect.zip from repository

### ISSUE THREAD

**Issue by KazumaMurao** [openpool/openpool-core#15]
The file "distribution/OpenpoolBaseKinect.zip" is the output of running ant. Every time we run ant, this file is modified. 

I would suggest to delete distribution/OpenpoolBaseKinect.zip from repository as we do not add binary files to the repository.

This is not so big problem for OSS. Plz let me ask your opinions casually.

**Comment by takashyx** [comment]
Agree and merged. Thanks! 
Then we need to put the binary package who are not familiar with building maybe... This will be another ticket.
