### ISSUE TITLE
All samples runs slower and slower.

### ISSUE THREAD

**Issue by camparijet** [openpool/openpool-core#9]
In the 4F Lab+cafe, all samples run slow gradually...

Processes continues for a long time with stable memory usage.

Thus it is not problems simply by memory leaks, I guess.

[HW Environment]
OS : Windows7 sp1 64bit
CPU : Core i7-3770
Memory : 8 GB

**Comment by camparijet** [comment]
[Suspected Points]
- Java Full GC is always running around 80mb
  -> Tuning Java VM Heap
  [ref (sorry japanese only)]
- http://software.fujitsu.com/jp/manual/manualfiles/M080099/J2UZ9570/03Z2A/tun07/tun00085.htm
- http://software.fujitsu.com/jp/manual/manualfiles/M080099/J2UZ9570/03Z2A/tun07/tun00091.htm
- http://www.syboos.jp/java/doc/full-gc-in-java-and-howto.html

**Comment by openpool** [comment]
SimpleOpenNI Version 0.27
0: SensorKinect/PrimeSense
1: SensorKinect/PrimeSense
[GC 15663K->6542K(62848K), 0.0032676 secs]
[GC 22990K->22010K(62848K), 0.0193361 secs]
[GC 37981K->37810K(62848K), 0.0165207 secs]
[Full GC 37810K->37807K(96000K), 0.0648619 secs]
[GC 54255K->55535K(111424K), 0.0144185 secs]
cam1_xoffset:31
cam1_yoffset:12
[GC 87037K->80139K(113216K), 0.0170764 secs]
[Full GC 80139K->80138K(163968K), 0.1280356 secs]
[GC 110443K->111170K(214080K), 0.0186708 secs]
FRAMERATE: 19.763958
FRAMERATE: 24.875841
[GC 165139K->146537K(218944K), 0.0196473 secs]
[Full GC 146537K->133256K(282496K), 0.1230401 secs]
FRAMERATE: 24.940289
[GC 182070K->183647K(315968K), 0.0243321 secs]
[GC 266185K->236512K(321984K), 0.0246071 secs]
[Full GC 236512K->157359K(368896K), 0.1423013 secs]
[GC 239649K->241648K(392064K), 0.0192187 secs]
[GC 339924K->289809K(399104K), 0.0210521 secs]
[Full GC 289809K->173199K(431360K), 0.1195597 secs]
[GC 271849K->273664K(451840K), 0.0229279 secs]
[GC 384699K->315856K(461760K), 0.0194384 secs]
[Full GC 315856K->185794K(488000K), 0.1225982 secs]
[GC 296726K->298483K(507392K), 0.0259866 secs]
[GC 416508K->327187K(520640K), 0.0183813 secs]
FRAMERATE: 30.229374
[GC 445512K->344516K(538368K), 0.0261279 secs]
[GC 465222K->349284K(556544K), 0.0206157 secs]
[GC 469901K->349252K(571904K), 0.0247191 secs]
[GC 468658K->348020K(584832K), 0.0186246 secs]
[GC 467418K->348052K(597696K), 0.0225814 secs]
[GC 471044K->351652K(604928K), 0.0190339 secs]
[GC 474661K->351652K(616704K), 0.0230918 secs]
[GC 479502K->356452K(621376K), 0.0207572 secs]
[GC 484326K->356484K(632896K), 0.0247550 secs]
[GC 490437K->362516K(636160K), 0.0220791 secs]
[GC 496483K->362484K(645376K), 0.0248414 secs]
[GC 502488K->368548K(648000K), 0.0215273 secs]
[GC 508472K->368516K(657152K), 0.0246699 secs]
[GC 513325K->373308K(659392K), 0.0224316 secs]
[GC 518123K->373316K(668160K), 0.0266706 secs]
[GC 525356K->380580K(668672K), 0.0247586 secs]
[GC 532645K->380580K(678016K), 0.0291525 secs]
[GC 539894K->387812K(679232K), 0.0262685 secs]
[GC 547108K->387812K(687680K), 0.0328198 secs]
[GC 553167K->393812K(689408K), 0.0291510 secs]
[GC 559136K->393780K(698368K), 0.0317409 secs]
[GC 565111K->399820K(700096K), 0.0305395 secs]
[GC 571031K->399820K(709312K), 0.0288721 secs]
[GC 577220K->405860K(711104K), 0.0281536 secs]
[GC 583307K->405828K(720384K), 0.0324880 secs]
[GC 589316K->411837K(722176K), 0.0288232 secs]
[GC 595326K->411893K(730688K), 0.0328768 secs]
[GC 600230K->416701K(732544K), 0.0309950 secs]
[GC 605032K->416709K(741120K), 0.0328617 secs]
[GC 611043K->422709K(742656K), 0.0293399 secs]
[GC 617086K->422741K(751424K), 0.0358875 secs]
[GC 623140K->428781K(753152K), 0.0339073 secs]
[GC 629175K->428789K(762240K), 0.0323884 secs]
[GC 635238K->434821K(764096K), 0.0327690 secs]
[GC 641315K->434821K(773056K), 0.0355232 secs]
[GC 647304K->440789K(774976K), 0.0354272 secs]
[GC 653040K->438397K(785024K), 0.0382936 secs]
[GC 658138K->447973K(786176K), 0.0365703 secs]
[GC 667725K->448013K(795712K), 0.0374813 secs]
[GC 672559K->452885K(798336K), 0.0349204 secs]
[GC 677484K->452925K(807808K), 0.0384636 secs]
[GC 683510K->458925K(809984K), 0.0377086 secs]
[GC 689490K->458861K(819392K), 0.0380863 secs]
FRAMERATE: 28.619843
[GC 695384K->464837K(821568K), 0.0390546 secs]
[GC 702463K->466005K(830656K), 0.0388729 secs]
[GC 708419K->470773K(833344K), 0.0371327 secs]
FRAMERATE: 30.127132
